### PR TITLE
Chapter 15 Updates

### PR DESCRIPTION
**Pull request by ciatog**
- Added missing favicon in counter app to remove console error
- Regressed back to beta 10 version of flex layout in ngAction as it was giving an OpaqueToken error with resolution found here: https://github.com/angular/flex-layout/issues/494

### CODE REVIEW

**Comment by yfain** [comment]
How to reproduce the OpaqueToken error?  I don't see it.

**Comment by ciatog** [comment]
Maybe it's environment and only shows up on my end? 

So when I run 'ng serve' on the client app the error would be displayed in the console while trying to compile. 

I didn't record the full error although here's another post that shows the exact error I got: https://github.com/angular/flex-layout/issues/509

**Comment by yfain** [comment]
Try the latest version beta-13 and see if it helps.

**Comment by yfain** [comment]
Actualy, when I upgraded to beta 13, I started getting this error

 ERROR in node_modules/@angular/flex-layout/media-query/breakpoints/break-points.d.ts(8,10): error TS2305: Module '"/Users/yfain11/Documents/angulartypescript/code-samples/chapter15/ng-auction/client/node_modules/@angular/core/core"' has no exported member 'OpaqueToken'.

**Comment by ciatog** [comment]
I'm guessing it's fine for 12 and when you originally ran this that was the
version available but for me I got 13 when I installed as that was just
released a short time ago. I'll set the dependency specifically to 12 and
see if that works for me

**Comment by ciatog** [comment]
That was it, 13 is the actual problem. When I specified 12 specifically the error disappeared. I've pushed that change as part of this PR

**Comment by yfain** [comment]
I've been using ^2.0.0-beta.13, but switching to ^5.0.0-beta.13 fixed the issue.

**Pull request closed without merging**
